### ISSUE TITLE
Need for a spec for config.toml?

### ISSUE THREAD

**Issue by kaushalmodi** [spf13/hugo#2597]
Hello,

We are in dire need of a spec that states:
- How the variables (keys, table names, keys in tables, etc) should be named in `config.toml`, what letter casing should be used consistently, etc.
- How those variables should be accessed inside templates.

Coming from a non-toml and non-go background, the current state does not seem to follow any spec.. some vars are all lower case, some are upper camel case and some are lower camel case.

See my minimum working example [here](https://discuss.gohugo.io/t/variables-not-pulled-from-config-file/1455/11?u=kaushalmodi).

There was also a recent commit related to config variables and cases that breaks hugo building that used to work on v0.17:

```
Started building sites ...
ERROR: 2016/10/17 10:38:29 general.go:236: theme/_default/summary.html is an incomplete or empty template
ERROR: 2016/10/17 10:38:29 general.go:236: theme/_default/li.html is an incomplete or empty template
ERROR: 2016/10/17 10:38:29 general.go:236: Error while rendering page post/generating-a-transparent-favicon.md: template: /home/kmodi/hugo/kaushalmodi.gitlab.io/themes/lanyon/layouts/_default/baseof.html:5:49: executing "main" at <.Site.Params.DateFor...>: invalid value; expected string
ERROR: 2016/10/17 10:38:29 general.go:236: Error while rendering page post/how-i-created-this-blog.md: template: /home/kmodi/hugo/kaushalmodi.gitlab.io/themes/lanyon/layouts/_default/baseof.html:5:49: executing "main" at <.Site.Params.DateFor...>: invalid value; expected string
ERROR: 2016/10/17 10:38:29 general.go:236: Error while rendering page post/elisp-meta-characters-in-string.md: template: /home/kmodi/hugo/kaushalmodi.gitlab.io/themes/lanyon/layouts/_default/baseof.html:5:49: executing "main" at <.Site.Params.DateFor...>: invalid value; expected string
```

This is what I have in my [`config.toml`](https://gitlab.com/kaushalmodi/kaushalmodi.gitlab.io/blob/f70ff44cebabe4311ece2ed5dfd3d6fa48733063/config.toml#L39-43):

``` toml
[params] # This NEEDS to be all lowercase. Capitalized 'Params' will NOT work
# https://github.com/tummychow/lanyon-hugo/issues/2#issuecomment-253274278
  Tagline = "Emacs, scripting and anything text oriented."
  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  DateForm = "Mon Jan 2, 2006"
```

And these are the contents in my `_default/summary.html`:

``` html
<article class="post">
    <header>
        <h1 class="post-title"><a href='{{ .Permalink }}'> {{ .Title }}</a> </h1>
        <div class="post-date">{{ .Date.Format .Site.Params.DateForm }} - {{ .FuzzyWordCount }} Words</div>
    </header>

    {{ .Summary }}

    <footer>
        <a href='{{ .Permalink }}'><nobr>Read more &rarr;</nobr></a>
    </footer>
</article>
```

**Comment by TiTi** [comment]
Yep I'm currently having trouble upgrading to v0.18(.1) because of my custom section in `config.toml`:

> [author]
>   name = "Thibault ROHMER"
>   email = "....@gmail.com"
>   github = "TiTi"
>   gaID = "UA-60799648-1"
> 
> [params]
>   notoc = true
>   disqusShortname = "thibaultrohmer"

> {{ if .Site.Author.gaID }}
> ...
> mailto:{{ .Site.Author.email }}
> ...
> {{ if isset .Site.Params "disqusShortname" }}


I manage to solve the author issue by renaming [author] to [Author] in config.toml (because case is now sensitive).
Note that: updating template to `{{ if .Site.author.gaID }}` did NOT help.

Right now I have NO compilation error but the google analytics condition does not work anymore: script is not included!

* `{{ if .Site.Author.gaID }}` compilation ok but section NOT rendered :-/
* `{{ if isset .Site.Author "gaID" }}` compilation ok but section NOT rendered :-/
* `{{ if .Site.Params.disqusShortname }}` compilation ok and section rendered
* `{{ if isset .Site.Params "disqusShortname" }}` compilation ok and section NOT rendered :-/

Definitely weird and breaking-change...

What should I put in both my config and my templates? Uppercase, lowercase ? sub-sections ?

**Comment by bep** [comment]
@TiTi try discuss.gohugo.io

**Comment by bep** [comment]
The params casing was fixed in Hugo 0.18.
